name: Setup the repository from template

on: [push]

permissions: write-all

jobs:
  setup-repository:
    if: ${{ github.run_number == 1 && !contains (github.repository, '/PyRobotIO-Template') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}' | tr '-' '_' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_URLNAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_OWNER=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
        shell: bash

      - name: Setup the repository
        run: |
          echo "Setup the repository with -a(author) ${{ env.REPOSITORY_OWNER }} -n(name) ${{ env.REPOSITORY_NAME }} -u(urlname) ${{ env.REPOSITORY_URLNAME }}"
          chmod +x .github/setup_repository.sh
          .github/setup_repository.sh -a ${{ env.REPOSITORY_OWNER }} -e ${{ github.event.pusher.email }} -n ${{ env.REPOSITORY_NAME }} -u ${{ env.REPOSITORY_URLNAME }} -d "${{ env.REPOSITORY_URLNAME }} created by ${{ env.REPOSITORY_OWNER }}"

      - name: Commit changes from template
        run: |
          echo "Commit the files, and push to base branch"
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit --message="Commit changes from template"
          git push
